### ISSUE TITLE
Deprecated use of `vscode.previewHtml`

### ISSUE THREAD

**Issue by Jayphen** [prisma/vscode-graphql#103]
The latest version of VSCode is giving this error when using the extension.

>Extension 'Prisma.vscode-graphql' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon. Please file an issue against this extension to update to use VS Code's webview API.

## Specifications

  - GraphQL for VSCode Extension Version: 0.1.7
  - VSCode Version: 1.32.1
  - OS Name: MacOS
  - OS Version: 10.14.3

**Comment by artisologic** [comment]
I now get `Error opening content.` when trying to run a query which I believe is the result of calling `vscode.previewHtml` so maybe it's now been deprecated… it means this functionality doesn't work currently.

**Comment by jaydenseric** [comment]
I'm getting `Error opening content.` too…

**Comment by divyenduz** [comment]
This is fixed in `0.1.8`
