### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by saxoboy** [prisma/vscode-graphql#105]
- Issue Type: `Performance`
- Extension Name: `vscode-graphql`
- Extension Version: `0.1.7`
- OS Version: `Darwin x64 15.6.0`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/Israel/Prisma.vscode-graphql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by divyenduz** [comment]
Please attach the profiling file and reopen a new issue.
