### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ipsum01** [prisma/vscode-graphql#106]
- Issue Type: `Performance`
- Extension Name: `vscode-graphql`
- Extension Version: `0.1.7`
- OS Version: `Linux x64 4.15.0-46-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/server/Prisma.vscode-graphql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by divyenduz** [comment]
Please attach the profiling file and reopen a new issue.
