### ISSUE TITLE
With nexus movement, can't we have only syntax highlight?

### ISSUE THREAD

**Issue by steida** [prisma/vscode-graphql#109]
This plugin does a lot. But I don't think we need more than syntax highlight with nexus. Am I correct?

**Comment by divyenduz** [comment]
Thanks for raising this issue! With Prisma moving to the [new datamodel syntax](https://github.com/prisma/rfcs/blob/0002-datamodel-2/text/0002-datamodel.md), we have a new extension for handling `.prisma` files: https://marketplace.visualstudio.com/items?itemName=Prisma.prisma

This extension would keep up supporting GraphQL files syntax though! Even when someone is not using nexus :) 

I am closing this issue, please re-open a new issue if you think this is not addressed properly.
