### ISSUE TITLE
v0.1.8 is incompatible with newest VS Code Insiders

### ISSUE THREAD

**Issue by furai** [prisma/vscode-graphql#114]
Hello,

I'm unable to get the latest 0.1.8 version of the plugin. Only 0.1.7 works. Can I somehow install newer version explicitly? 

## Specifications

Version: 1.35.0-insider
Commit: 553cfb2c2205db5f15f3ee8395bbd5cf066d357d
Date: 2019-06-04T00:08:32.039Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.1.6-050106-generic

Cheers,
Furai

**Comment by jameshood118** [comment]
I updated my vscode yesterday to 1.35.0 (unclear if its insider or not, i dont think it is) and the extension has been disabled (not by me)

**Comment by wuelcas** [comment]
Same as @jameshood118, VS Code got updated when I opened it today and the extension was disabled automatically. There's no messages in the Output console

**Comment by furai** [comment]
I've fixed it form myself for now till the issue is resolved here in the repo. Steps to follow:

1. Uninstall already installed add-on (I don't know if it's required but I did it anyway.),
2. Download add-on from https://marketplace.visualstudio.com/items?itemName=Prisma.vscode-graphql.
3. Unpack/Edit the .vsix file:
    - Edit `extension.vsixmanifest`
      - Replace value of `<Property Id="Microsoft.VisualStudio.Code.Engine" Value="1.34.0" />` with `1.35.0` for latest stable and `1.36.0` for latest insider version.
    - Edit `extension/package.json`:
      - Replace value of (line 24) "vscode": "1.36.0" with `1.35.0` for latest stable and `1.36.0` for latest insider version.
4. Go to your extensions in VSCode and from the cog at the top-left choose install extension from VSIX. 
5. Enjoy.

If you CBA to do these changes I can send you my modified version but I think that instructions above are easy enough to follow. I figured it out and I'm no VSCode extensions developer.

**Comment by divyenduz** [comment]
@furai Thanks for reporting this and pushing this forward. This should be fixed in `0.1.9`. 

I am closing this issue, please re-open if the problem persists.
