### ISSUE TITLE
Embed not highlighting properly in datamodel.prisma

### ISSUE THREAD

**Issue by mckernanin** [prisma/vscode-graphql#120]
## Actual Behavior
Embeds look like this in a `datamodel.prisma` file:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/6300047/60244792-6c2e9380-9878-11e9-8c04-c944cbcdeb1f.png">

## Expected Behavior
Should be highlighted properly and not show an error in the editor:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6300047/60244868-97b17e00-9878-11e9-9ebb-9ae0b7b9221e.png">

## Steps to Reproduce the Problem Or Description
Paste the following into `datamodel.prisma` file, with the extension installed:
```
embed Address {
  street String
  city String
  state String
  zip String
}
```

## Specifications

  - GraphQL for VSCode Extension Version: 0.0.12
  - VSCode Version: Version 1.36.0-insider
  - OS Name: macOS Mojave
  - OS Version: 10.14.5

## Logs Of TS Server || GraphQL Language Service
```
[Info  - 1:04:11 AM] Using tsserver from: /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib
[Info  - 1:04:11 AM] <main> Forking...
[Info  - 1:04:11 AM] <main> Starting...
```

**Comment by divyenduz** [comment]
This is the GraphQL extension, I think that the extension that you are referring to is: https://marketplace.visualstudio.com/items?itemName=Prisma.prisma

This extension no longer deals with the `.prisma` files but the one linked above does. 

Can you confirm?

**Comment by divyenduz** [comment]
I am closing this one, please re-open if the issue persists.
