### ISSUE TITLE
Why this is in themes category on VSCode marketplace?

### ISSUE THREAD

**Issue by deadcoder0904** [prisma/vscode-graphql#121]
I was checking all my installed themes & I don't understand why this should be in theme category. 

Themes are well, themes 😂 

Kindly remove it :)

To check paste `@installed @category:themes` in VSCode's Extensions bar.

**Comment by divyenduz** [comment]
@deadcoder0904 : Thanks for raising this, can you please make a PR to remove it?

**Comment by deadcoder0904** [comment]
Ohh I never made a VSCode extension myself so don't know if it's through the code or the Web UI. A quick google didn't help either. Sorry :(

**Comment by divyenduz** [comment]
I think we just need to [remove this](https://github.com/prisma/vscode-graphql/blob/master/package.json#L30). 

These are the relevant [docs](https://code.visualstudio.com/api/references/extension-manifest#marketplace-presentation-tips), please search for `Category`.

**Comment by deadcoder0904** [comment]
Done 🎉
