### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by ganemone** [prisma/vscode-graphql#131]
Can we release a new version? There have been lots of improvements since the last release.

**Comment by HosseinAgha** [comment]
@divyenduz We are patiently waiting for the `v0.1.4` release.

**Comment by divyenduz** [comment]
I am sorry about the delay, I will do it today evening.

**Comment by divyenduz** [comment]
Couldn't get to it yesterday, today evening it is 🙏

**Comment by divyenduz** [comment]
`0.2.2` is published, sorry about the delay 🙏
