### ISSUE TITLE
File Resolution inconsistent

### ISSUE THREAD

**Issue by ChiefORZ** [prisma/vscode-graphql#35]
While using Intellisense in an `.graphql` file, the vscode debug tab for **GraphQL Language Server** sometimes throws the following error:

```
ZEBRA: GraphQLProjectConfig {
  config: 
   { schemaPath: 'packages/api-graphql/src/schema.graphql',
     includes: [ '**/*.graphql' ],
     extensions: { endpoints: [Object] } },
  configPath: 'e:\\dev\\gql-demo\\.graphqlconfig.yml',
  projectName: 'app' } e:\dev\gql-demo\packages\api-graphql\src\schema.graphql
(node:14416) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 45): Error: ENOENT: no such file or directory, open 'e:\e%3A\dev\gql-demo\packages\react-apollo\src\queries\posts.graphql'
```
i could imagine that it is a Windows-only problem 😉

**Comment by divyenduz** [comment]
This is released in 0.1.4 (which is a preview release with CodeLens feature as well) 🎉 

Feedback please 👍👇 
![](http://g.recordit.co/KMsQhNflnF.gif)

**Comment by ChiefORZ** [comment]
@divyenduz nice feature!

but no, i meant following error:

the extension tries to open the file `e:\e%3A\dev\gql-demo\packages\react-apollo\src\queries\posts.graphql` - this is the file im currently in.
this path is not a valid path...

somehow he attaches the drive twice to the beginning of the path, once normal and once escaped/encoded: **e:\e%3A\**

**Comment by dontsave** [comment]
Running into this as well
