### ISSUE TITLE
graphql as tagged template

### ISSUE THREAD

**Issue by azdanov** [prisma/vscode-graphql#49]
Is there a way to use `graphql` template tag instead of `gql`?

I am trying out [gatsby.js](https://www.gatsbyjs.org/) which uses relay for it [queries](https://www.gatsbyjs.org/docs/querying-with-graphql/#what-does-a-graphql-query-look-like).

__Edit:__
I tried `import { graphql as gql } from 'graphql-relay';` but it doesn't seem to validate against a pre generated schema.

<img width="470" alt="screen shot 2018-07-09 at 07 18 19" src="https://user-images.githubusercontent.com/6123841/42430493-4c3a6f68-8348-11e8-80b3-b1665b58730b.png">

Similar query using [intellij-graphql](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/):

<img width="467" alt="screen shot 2018-07-09 at 07 19 45" src="https://user-images.githubusercontent.com/6123841/42430521-7c3f09b2-8348-11e8-9a31-4cbd6133c11c.png">

**Comment by divyenduz** [comment]
This can be achieved in the following two ways

1. Adding `graphql` to the list of supported tags [here](https://github.com/divyenduz/ts-graphql-plugin/blob/master/src/index.ts#L18)

2. Making this list configurable by editor settings. 

I will see if this can be picked up shortly.

**Comment by rdrey** [comment]
Thanks @divyenduz 

I'm running 0.0.10 now and see the little  :electric_plug:  GraphQL in the status bar and the GraphQL Language server starts, but I don't get any completions in my snippets yet. I can run the `extension.isDebugging` command and it logs false.

Is there a step I'm missing or an easy way to enable more debugging?

**Comment by divyenduz** [comment]
This is released in 0.1.4 (which is a preview release with CodeLens feature as well) 🎉 

Feedback please 👍👇 
![](http://g.recordit.co/KMsQhNflnF.gif)
