### ISSUE TITLE
Autocomplete in gql tags still not working on 0.1.4

### ISSUE THREAD

**Issue by cburbank** [prisma/vscode-graphql#61]
The 0.1.4 release notes mention #21 being fixed but it seems that it's still broken. I've tested in both my own project and the example repo posted in that issue (https://github.com/ntziolis/vscode-graphql-extension-gql-test) and autocomplete inside `gql` tags is not working in either.

**Comment by pantharshit00** [comment]
@divyenduz

**Comment by cburbank** [comment]
Hi @divyenduz , thanks for looking into this.

Here is the debug output. There is a line that mentions this extension:

`Extension 'Prisma.vscode-graphql' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305`

```
/Applications/Visual Studio Code.app/Contents/MacOS/Electron --debugBrkPluginHost=43516 --debugId=3e953b1e-877e-4911-afb4-88dd49573874 --extensionDevelopmentPath=/Users/chrisburbank/workspace/vscode-graphql 
vscode-customcss is active!
extension.js:12
Git extension API method 'getGitPath' is deprecated.
main.js:1
[CoenraadS.bracket-pair-colorizer] Accessing a window scoped configuration for a resource is not expected. To associate 'bracketPairColorizer.excludedLanguages' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.
extensionHostProcess.js:571
rejected promise not handled within 1 second
extensionHostProcess.js:848
Extension 'Prisma.vscode-graphql' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
extensionHostProcess.js:799
[CoenraadS.bracket-pair-colorizer] Accessing a window scoped configuration for a resource is not expected. To associate 'bracketPairColorizer.excludedLanguages' to a resource, define its scope to 'resource' in configuration contributions in 'package.json'.
extensionHostProcess.js:571
No editors associated with document: /Users/chrisburbank/workspace/vscode-graphql-extension-gql-test/tsconfig.json
documentDecoration.js:318
```

The GraphQL Language Server output was empty in the vscode instance running the extension:

![image](https://user-images.githubusercontent.com/15691227/45898657-9d89a880-bda8-11e8-87c3-3795e189a56c.png)

**Comment by divyenduz** [comment]
@cburbank : Thanks! did you also follow the grep part of the debug log? I think this is all of the log but I want the logs generated by the extension which would be in 

`tail -f <ts_log path> | grep ts-graphql-plugin-log`

**Comment by divyenduz** [comment]
Please notify me via a comment here if this issue still exists, I will reopen the issue.
