### ISSUE TITLE
When no .graphqlconfig is being found, extension should fail silently

### ISSUE THREAD

**Issue by timsuchanek** [prisma/vscode-graphql#7]
![image](https://user-images.githubusercontent.com/1094804/41276950-1408be9c-6e26-11e8-88cb-e5ba5db6c6ac.png)
In my case, the .graphqlconfig extension is in a sub directory.

**Comment by lirbank** [comment]
To make onboarding easier perhaps the config file should be optional? To get started I just added an empty JSON object `{}` in `.graphqlconfig`. The plugin then works, so it may as start up without any config at all (you still get syntax highlighting, formatting, etc).

Not saying it should "fail silently" - but enabling incremental onboarding is a nice thing - I think. Like eslint - you don't need a config (I think?), once you're up and running you can start to add rules as you like (though I realize most people start with the recommended config, but still).

But at the same time it's a mess if you have a config and it's not loaded (perhaps it's in the wrong dir). What about a message in the console "GraphQL Language Server started without config"?

Just my thoughts.

**Comment by loicplaire** [comment]
@timsuchanek out of curiosity, did you get the extension working when the `graphqlconfig.yml` file is in a subdirectory?

I have a project using `lerna` so the config file isn't in the root but in `packages/package-name/.graphqlconfig.yml` and I get the exact same warning showed in your screenshot. 😢

**Comment by AndrewIngram** [comment]
I have a project which happens to generate `.graphql` files, but doesn't use them as source, so it doesn't make a lot of sense to use the plugin for anything beyond syntax highlighting. But if I happen to view the file, I get this error, which isn't a nice developer experience.

I understand the argument in favour of having the error for a misconfigured `.graphqlconfig`, but I wouldn't show it for a missing one.

**Comment by divyenduz** [comment]
Thanks all for the detailed feedback. After the initial feedback, I think that the extension should be indeed silent about the graphql config file, that would be an incremental experience as the extension already works with `graphql` files without needing a config for features like syntax highlighting. I will take that up soon. 

@loicplaire : Currently, it needs the config file to be at the root. That issue is being tracked here https://github.com/prismagraphql/vscode-graphql/issues/24

**Comment by zackkrida** [comment]
I experience the message in the original post on projects that _aren't even using_ graphql. Strange.

**Comment by divyenduz** [comment]
This is fixed and released in `0.1.6` 🎉 
Sorry for the delay in resolving this 🙏
