### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by sidharthachatterjee** [prisma/vscode-graphql#96]
I added a minimal `.graphqlconfig` as documented in https://github.com/prisma/graphql-config with the following:
```
{
  "schemaPath": ".cache/schema.graphql"
}
```
Autocomplete doesn't work though. Am I missing something?

**Comment by divyenduz** [comment]
@sidharthachatterjee : Thanks for raising this. Can you please see if there is an error in the [output logs for "GraphQL Language Service"](https://github.com/prisma/vscode-graphql#a-testinglogging-graphql-language-features).

**Comment by divyenduz** [comment]
Also, to make language features like autocomplete work, please refer to [usage](https://github.com/prisma/vscode-graphql#usage) section. Although, there might be a bug (https://github.com/prisma/vscode-graphql/issues/93) that prevents this from working in some cases, I am investigating that.

**Comment by yantrab** [comment]
Not working for me either. can you give as a simple work repo?

**Comment by thu-san** [comment]
Me 3 :)

**Comment by twocucao** [comment]
not working , could you offer a minimal working repo?

**Comment by 5achinJani** [comment]
Not working for me too. #75

**Comment by divyenduz** [comment]
Please notify me via a comment here if this issue still exists, I will reopen the issue.
